travis:
  secure:
    BINSTAR_TOKEN: TNKfFl7kckDhoemEGDm0yHRWMG2Rf/NZUavDep+ljf2DP9KE+SY6HOfSEPiB85fvr/VdPoKi5yT3sMUP9/3ocqXy8zxSYKzKcb3FSlgRjmFf66iyMmBMsnKGaUzlohY7L8uHHFIUn1x8v6Jub7LQDgMAKaxTLd/BdcGTBP4+9N8DxS627n4yUf4KO8zdLXQw21s9qXyhiJ76LJ5T41qTNH9U3M4ZVgy15z1BYYWVp1CXoErFB7fZozwrXTg4Egldi/T47May2kYr3IV6n8xBkDZ2EPdMvr8aVbTCN4L7agnfv2GeJCY008mobn30t9T6qiFzri8GlItyd5L3PDqU2smP8ALCB04nGYx0Hyjhdfy/5SYNnSEQFOfLfw0AkyIdn9ZLAjR8eGvxnkO2/SVCs5Do/l5j6N+H7m8J+IQa1faaWCgUiiwJUHYLNh92/SasS5rpkPRLyJSCwPvpKr8woOkCrxuwwJiSle58dao2umCJDq6/n5I7nGJaHPhcS4fA15bJ4XNDs6OlXXIccCZ/lFriV0XdqEjTP+jOsP5qg05O3baM3n5Ti+lhhXC+MMzCCIA/QrW/r7yC1T3pRWdsTlhk5z5GCGwEaI28XlbuIT7K6PUJqx00K+szECgYu04t/bzheRfa6MMn9CMuEb6WoQLxkMf6o2qluU6qpUwcW7Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
