travis:
  secure:
    BINSTAR_TOKEN: l2JMLA1eixShvnynwWZt+/cIiuE5sKmIKWdgT8rcecgAmz168jfuEphCb3W4PzkEcEE0xPJ6fij0C1V0Nb58ueS+L4My2y0MJUeOOj7DsYMU4Khs8oq5F28eD3emUUqzZmkX3legWtxNtMRP1gQQ/Uwdn64RjcB+oR9GrvNf0HQvBwkHrNyPisuRtDMJH93wx9ZQFl4Zta7DpzEDebe6nDrIewJ2ckqIu6fxtTJWqKekwXKSm72cYUusAXc4BZxd/9eSlJ8/7UFDdJrMHxYpmI9QCO/NYYBUN/2pbGvY3PRYDlPrg9qgVgCe3YZLbVyH0GQHkGh0j3y4PupRyV1xIHLxE8W0+Gx5KkHV3VReYPXRUxFBTL9c2dLtRFKHbgZ/h/cPGITnDnpd2qZ6KnNv0sdNaZmjEGq2sSV1nWYFR5UWnRAmncZ246XbjxILhsXfYKcz8B01tqGi42MwXTMOpRfwV9o+XD5YX4KD8w3bZtqNnmEDaBKjmowbXGtSHgB78hmL+ZRXhjxJoRcyIWY30dTKznhSsUtB7J0s5v8G4HIhOqNvbXogrwprGHPjtFyjGl/o4Rh93j561sdS6wO25vTAjQYzh6KOYFus5sdgcb0T4eB4VRKRDOwkhgOD8v9VVuY0txNu7SCNSmyUXuwLRrXOBHoXSy4r/lXqUc4aP+M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
