travis:
  secure:
    BINSTAR_TOKEN: VLUFkF4N5dCLrQG2a+EyhzpULI04Bv6sW2wtod3uWXqRGPoJJKGG1//yvdxp7SBrmnLfnff72iDINhYoIivEuYJJEiajVwLX7alyzdmdYrngQC0VzPHiTtKwzm0IBWNb+h9zJBG+nbH96wxAJuoCoz7SlmOGieYnUuMVP3abMA5d2bSvdP+KpTOkcOL8AWuK7AIJ1b2E0+RVloFb8rDwPfSLrICoLt2HAyYAdoiTJt/BGWezg/jMRkkVIjdW41Ip6UUafeWMS+7gGVO9VcauXFv7GRopsCmYeagDGSL1u1adHOnM2tFqwE7cjtrYggFrIJjNBkSQwYqZuIAMltAB65zK+wS0zxKCYojDjvvn3ZNO57YGNmCbe7lFwjCt1E/MxuX3zBebasN6G0QTgadALp7h0kha5N8S4vQKzxxALZm71ajv44OKAwrSATEQpxYBusG7tzYn0EJ9viQXde05WUAFGmTmyUlaM+xwozpX63br+2Y3IexXwrLA1q3wdspYe15JrH+yU/aoua1p1jdxnOEsgcVYP22tO5FPyoSkgb1e+amidV29WHci30DFlwNMcmz5ryndrzcvEl4DMG18tHzrCXS+Xc7PwmZvhAT3OQ4I+bDzbCtHytang8aGdAC7T42v0HKXLDeM+FB9FLwgznqLcwecI1XDDVH2aRv2MI4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
